### ISSUE TITLE
Change license to MIT?

### ISSUE THREAD

**Issue by ringods** [vatesfr/xo-sdk-go#1]
@olivierlambert,

You created this repo with the LGPL license in place. The intent is to extract the SDK code from https://github.com/terra-farm/terraform-provider-xenorchestra into this repository. The current Terraform provider code is MIT licensed. If we move the code, we would actually be re-licensing the code.

Can you elaborate why you want this to be LGPL?

@ddelnano what is your take on this?

**Comment by olivierlambert** [comment]
We usually use aGPLv3 at Vates. For a lib, I thought LGPL was better suited.

I'm not a license expert, what's the pro of MIT vs LGPL?

**Comment by ringods** [comment]
Go, statically linking and LGPL don't go very well together.

https://medium.com/@henvic/opensource-and-go-what-license-f6b36c201854

Please allow for a more permissive license like MIT.

**Comment by olivierlambert** [comment]
Okay I didn't know that. Changing the license then.
