### ISSUE TITLE
host.Compare returns true if one of the variables match 

### ISSUE THREAD

**Issue by arpanadhikari** [vatesfr/xo-sdk-go#6]
Hi there! 

Not sure if this is a intended behaviour in the sdk, but when comparing two hosts, the sdk returns true if one of the Id, Pool or NameLabel match.

This can be an issue if we're comparing two hosts in the same pool? 

[code-ref:](https://github.com/vatesfr/xo-sdk-go/blob/adefa034d12b0db67f6aec97d9df24a2c19325c8/client/host.go#L24-L36)
```golang
func (h Host) Compare(obj interface{}) bool {
	otherHost := obj.(Host)
	if otherHost.Id == h.Id {
		return true
	}
	if h.Pool == otherHost.Pool {
		return true
	}
	if h.NameLabel != "" && h.NameLabel == otherHost.NameLabel {
		return true
	}
	return false
}
```

Happy to make a pull request if this is considered a potential opportunity for improvement.

**Comment by ddelnano** [comment]
@arpanadhikari sorry for the late reply! I was traveling the past few weeks.

This code was written with that particular purpose in mind. The only consumer of this client that I'm aware of is the [terraform-provider-xenorchestra](https://github.com/terra-farm/terraform-provider-xenorchestra), where this client code was initially developed.

The idea behind designing it this way was to treat the argument to [Client.FindFromGetAllObjects](https://github.com/terra-farm/terraform-provider-xenorchestra/blob/51c49b950466c47befa6860263ac8a47e9da55a7/client/client.go#L257) as a filter. Depending on the fields set on the struct (such as the `Pool` field), it will return anything that matches. The terraform provider needs to filter on all hosts that are within a pool in this way [here](https://github.com/terra-farm/terraform-provider-xenorchestra/blob/51c49b950466c47befa6860263ac8a47e9da55a7/xoa/data_source_hosts.go#L49-L51).

I am planning to rethink how this xo-sdk-go client code works soon (in https://github.com/terra-farm/terraform-provider-xenorchestra/issues/189). So I would love to hear more about how you'd like to use this client and how its existing design isn't solving your use case.

**Comment by arpanadhikari** [comment]
I see, thanks!
